### ISSUE TITLE
ScrollTop not starting at 0.

### ISSUE THREAD

**Issue by Mrbeyond** [Paratron/hookrouter#127]
Whenever I route to a new page, the scroll bar is not changing. Normally it is supposed to start at (0,0) but  is only sticky to the last position of previous page; it is quite frustrating. Please I really need help with this.

**Comment by Paratron** [comment]
This happens because when navigating with hookrouter, you are not _really_ navigating. A new, virtual URL will be pushed to the browser history, the page remains the same and React will only re-render the DOM.

Because technically no real navigation is happening, the browser won't scroll to the top.

Here is, what I would do:

First, let's create a hook that scrolls to the top, when a component is mounted:

```javascript
import React from 'react';

const useScrollToTop = () => {
	React.useEffect(() => {
		window.scrollTo(0, 0);
	}, []);
}
```

Then, you can import and use that hook in your page components:

```JSX
const AboutPage = () => {
	useScrollToTop();

	return (
		<div>
			<h1>About me</h1>
			<p>
				Lorem Impsum
			</p>
		</div>
	);
};
```

I hope this resolves your problem! 👍

**Comment by Mrbeyond** [comment]
Sorry for the late reply. Thanks it really works well.
