### ISSUE TITLE
Feature: Basepath for non-root apps

### ISSUE THREAD

**Issue by FredyC** [Paratron/hookrouter#18]
It's a bit unrealistic to refactor a bigger application routing at once. It is partially related to a propose static route #15 for testing. It would make sense if we could set an path prefix to specify where is that routing table sitting right now. Something like this.

```js
const routeResult = useRoutes({
  '/category': () => <MenuCategoryListPage />
}, '/settings/menu')
```

I made myself a simple function that adds that prefix to those routes. Only later I've realized it's not enough because `navigate` and `useRedirect` won't take that into account. It needs to be in the context to be really useful.

**Comment by Paratron** [comment]
You mean a basepath setting for when your app does not run on the root of a domain?Thats definitely necessary.

**Comment by Paratron** [comment]
Implemented in `1.1.0`.

Call `setBasepath(basepathString)` before your app starts rendering (ideally in your index.js) and you are fine 👍

**Comment by FredyC** [comment]
Hm, that doesn't much sense why it should be global while routing is happening locally in each component basically. Why shouldn't I be able to change the base path in that particular component and lower?

Also what happens if I do that later? I mean one of our apps is discovering a routing base path through the backend call (for various reasons). I was kinda hoping in the declarative API as I outline above. I am afraid this isn't enough.

Would be great if you would be communicating solutions before you implement them. It's not very effective like this :)

**Comment by Paratron** [comment]
Routing is not happening locally. It is based on `location.pathname` and is reduced down from there.  Calling `setBasepath()` before anything happens is necessary to tell the router: "Hey, ignore this beginning part of the path" (amongst other stuff).

Technically, you _can_ call the setter any time, you just need to make sure to re-evaluate any routes afterwards. Since routing is not possible without the base path anyways (because your matches will fail), you can postpone your applications rendering util you retrieved the base path. The solution you suggested above would need the base path to be passed to the `useRoutes` hook every time (which also leaves you with the problem to retrieve it, first). The problem is that `navigate()` and `<A>` also need access to the base path - thats not possible with your approach.

I am afraid the base path API will stay as it is.

**Comment by FredyC** [comment]
Yea, I am afraid that as much as you got a great idea here (in general), I am not too fond of quirks you are introducing into it. Global state is just wrong in React world. Once the Concurrent gets more polished, this will die as quickly as it has started in my opinion.

So at this point, I am pretty waiting for you to figure some basics and then I will do my own rewrite that actually makes sense :) Sorry, to put it out so bluntly, but you apparently have your own path to follow and you are not really interested in listening to the community so I am not going to be bothering you anymore.
