### ISSUE TITLE
Optional parameter support

### ISSUE THREAD

**Issue by bvalyou** [Paratron/hookrouter#28]
I have a component where you can set one id as active and navigate to it without a url parameter from the nav, but there is an optional url parameter that acts as an override.

As a workaround, when I was converting my application over from React Router, I made two routes, one with the param and one without, but it would be convenient to consolidate with an optional param.

For reference here's the before and after for that component.

```
// react-router (I made a custom HOC to clean up the API)
export const routes = [{
	path: '/',
	exact: true,
	component: List,
}, {
	path: '/create',
	component: Create,
}, {
	path: 'edit/:id?',
	component: Edit,
}, {
	path: '/view/:id?',
	render(props) {
		return <Edit readOnly {...props} />;
	},
}];
```

```
// hookrouter
const routes = {
	'/': () => <List />,
	'/create': () => <Create />,
	'/edit': () => <Edit />,
	'/edit/:id': ({ id }) => <Edit id={id} />,
	'/view': () => <Edit readOnly />,
	'/view/:id': ({ id }) => <Edit id={id} readOnly />,
};
```

This is definitely a nice to have, and as you can see from this example it's already cleaner using hookrouter, but if we could accommodate for optional parameters I could get rid of a couple extra lines of code.

**Comment by Paratron** [comment]
Yeah, it would save you a few lines in this example but would make the url parameter parsing and route matching way more complex. So the lines saved here would be added three times into the hookrouter core.

The real problem here is feature creep, or "one component to rule them all". Try splitting up view and edit into separate components.

Also, `/view` without id doesnt make sense. What should it display? Same goes for `/edit` without id. At first I thought it would be for creating entities but than there is also a `/create` route...

**Comment by sendittokeith** [comment]
I do have the use case where I create/edit from same route and would also like optional for this and other reasons...
/user   (no param passed is new, else edit)
/search (could pass n number of parameters)
