### ISSUE TITLE
'routeResult' component not updating when props change

### ISSUE THREAD

**Issue by timraybould** [Paratron/hookrouter#34]
I've spoke about this before but still having an issue. Going to try a different approach to explaining it.

    function ParentComponent () {
        const [value, setValue] = useState(1)
        const routeResult = useRoutes({
            '/': () => <ChildComponent value={value} setValue={setValue} />
        })

        return (
            <div>
                {routeResult}
            </div>
        )
    }

and separately,

    function ChildComponent (props) {
    
        function changeToTwo() {
            props.setValue(2)
        }

        return (
            <div onClick={changeToTwo}>
                {props.value}
            </div>
        )
    }

In this simplified example, the value rendered on screen via ChildComponent does not update from 1 to 2, even though the ParentComponent is aware of the change. Without hook router in the picture, the child component updates because its props do. However with hook router, it does not. Is this intentional or a bug?

**Comment by Paratron** [comment]
The reason this does not work is that hookrouter will cache the return value of the result function. This speeds up performance because it assumes route result functions to be pure (I should mention that in the docs). Your route result function is _not_ pure and relies on outside variable. Because hookrouter caches the result, it is "frozen" to the `value` of the initial render: `1`.
