### ISSUE TITLE
Proposal for Redirect component

### ISSUE THREAD

**Issue by avkonst** [Paratron/hookrouter#59]
Nice library. I have migrated to this from react-router. One issue I encountered is there is no analogy of react-router Redirect component. This component replaces the current item in history by the provided one and navigates the page to the provided path.

- I have created one myself like the following below, but I am not sure if it correct way of doing this. Could you please comment?
- I think this could be included to your library. What do you think?

```tsx
import React from 'react';
import { navigate } from 'hookrouter';

export const Redirect = (props: { href: string }) => {
    navigate(props.href, true);
    return <></>;
};
```

**Comment by timsu** [comment]
This would be great for "catch-all" redirects too, which the current useRedirect hook doesn't handle well:

```
const routes = {
    '/': () => <HomePage />,
    '/about': () => <InfoPage />
    '/*': () => <Redirect href='/' />
}
```

**Comment by Fxlr8** [comment]
Why not just do this?
```
const routes = {
    '/': () => <HomePage />,
    '/about': () => <InfoPage />
    '/*': () => <HomePage />
}
```

**Comment by slevy85** [comment]
@Fxlr8 , your solution works as a catch-all route, but the url in the browser will not be changed, so for the user it may be less practical.
With a `Redirect` component the url changes back to the one wanted.

**Comment by Paratron** [comment]
The library has been written to finally stop using components for logical things. Components should be used to represent UI elements rather than programming logic. There may be people who feel comfortable "programming" in XML but not me - this is the philosophy of this lib. 

If you'd like to make a "redirect", feel free to call `navigate()` any time. Even within a render function - it doesn't matter where you call it. The current `useRedirect()` hook does basically the same.

**Comment by brneto** [comment]
@Paratron, it's as good point but then how would you recommend to do when I would need to redirect based in some conditions. Something like:
```javascript
if (isCondition) {
  useRedirect(currentLocation, nextLocation);
}
```

Since it would break the [Rules of Hooks](https://reactjs.org/docs/hooks-rules.html).
